# [target.thumbv7em-none-eabi]
# runner = "arm-none-eabi-gdb -q -x ./openocd.gdb"
# rustflags = [
#   "-C", "link-arg=-Tlink.x",
# ]
[target.thumbv7m-none-eabi]
runner = 'probe-rs run --chip STM32F103C8'
rustflags = [
    "-C",
    "link-arg=-Tlink.x",
    #"-C", "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv7m-none-eabi"

[env]
DEFMT_LOG = "info"
